import type { Metadata } from "next";
import { Bebas_Neue, DM_Sans } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import Header from "@/components/Header/Header";
import CartDrawer from "@/components/CartDrawer/CartDrawer";
import Footer from "@/components/Footer/Footer";
import { fetchProducts } from "@/lib/api";

const dmSans = DM_Sans({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-display",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const { logo, title } = await fetchProducts();

  return (
    <html lang="en" className={`${dmSans.variable} ${bebasNeue.variable}`}>
      <body>
        <CartProvider>
          <Header logo={logo} title={title} />
          {children}
          <Footer title={title} />
          <CartDrawer />
        </CartProvider>
      </body>
    </html>
  );
};

export default RootLayout;
