  import type { Metadata } from "next";
  import { Geist, Geist_Mono } from "next/font/google";
  import "./globals.css";
  import { CartProvider } from "@/context/CartContext";
  import Header from "@/components/Header/Header";
  import { fetchProducts } from "@/lib/api";

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  const RootLayout = async ({ children }: { children: React.ReactNode }) => {
    const { logo, title } = await fetchProducts();

    return (
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body>
          <CartProvider>
            <Header logo={logo} title={title} />
            {children}
          </CartProvider>
        </body>
      </html>
    );
  };

  export default RootLayout;